[package]
name = "rodnix-daemons"
version.workspace = true
edition.workspace = true

[[bin]]
name = "device-manager"
path = "src/device_manager.rs"

[dependencies]
rodnix-lib = { path = "../lib" }

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1

